/*
*  HdmsgHost.c
* HDMSG
*
 *  Created on: Feb 7, 2022
 *     Author: Ebenezer Komla Gavua
*/
#include <stdlib.h>
#include <stdio.h>
#include "HdmsgHost.h"
#include <math.h>
#include <ctype.h>
#include <string.h>
#include <sys/wait.h>
#include "xbt/log.h"
#include "xbt/asserts.h"
#include "xbt/xbt_os_time.h"
#include "xbt/sysdep.h"

/* Globals */
double MAP_CALIBRATION_FACTOR;
double REDUCE_CALIBRATION_FACTOR;

long input_size;
long hdfs_chunk_size_bytes;
long input_size_bytes;
long hdfs_chunk_size;
long mappers;
long reducers;
long reducers_2;
long reducers_3;
long reducers_4;
long hdfs_chunk_size_bytes_2;
long hdfs_chunk_size_bytes_3;
long hdfs_chunk_size_bytes_4;


int TaskReceive(int argc, char * argv[]);
int random_int(int min, int max);


//TODO:  set map tasks cost!

/* Definition of the the method utilized for generating the quantity of chunks of data uploaded from HDFS.
 * It is generated by dividing the input_size_bytes by the hdfs_chunk_size_bytes. */

double get_map_cost(msg_host_t h)
{
   double flops_per_mb = 0.004500;
  return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_1(msg_host_t h)
{
	double flops_per_mb =0.0001273;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
   return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_2(msg_host_t h)
{
   double flops_per_mb =0.0001365;
   double rand_num = random_int(20000,40000);
   flops_per_mb *= rand_num/20000;
   return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_3(msg_host_t h)
{
    double flops_per_mb =0.0007162;
    double rand_num = random_int(2000,4000);
    flops_per_mb *= rand_num/2000;
   return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_4(msg_host_t h)
{

   double flops_per_mb =0.000248;
   double rand_num = random_int(2000,4000);
    flops_per_mb *= rand_num/2000;
   return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_5(msg_host_t h)
{

    double flops_per_mb =0.0007062;
    double rand_num = random_int(2000,4000);
    flops_per_mb *= rand_num/2000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}


double get_map_cost_6(msg_host_t h)
{
     double flops_per_mb =0.0007062;
     double rand_num = random_int(20000,40000);
    flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_7(msg_host_t h)
{

     double flops_per_mb =0.0002918;
     double rand_num = random_int(20000,40000);
     flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}
double get_map_cost_8(msg_host_t h)
{
    double flops_per_mb =0.000109;
    double rand_num = random_int(20000,40000);
    flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_9(msg_host_t h)
{
	double flops_per_mb =0.00016;
     double rand_num = random_int(20000,40000);
    flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}


double get_map_cost_0(msg_host_t h)
{
   double flops_per_mb =0.0001;
   double rand_num = random_int(20000,40000);
   flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_11(msg_host_t h)
{
    double flops_per_mb =0.084296;
   double rand_num = random_int(20000,40000);
  flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_12(msg_host_t h)
{
    double flops_per_mb =0.084296;
    double rand_num = random_int(20000,40000);
    flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_13(msg_host_t h)
{
    double flops_per_mb = 0.00047100;
    double rand_num = random_int(20000,40000);
   flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}

double get_map_cost_14(msg_host_t h)
{
    double flops_per_mb = 0.00016100;
    double rand_num = random_int(20000,40000);
   flops_per_mb *= rand_num/20000;
    return MAP_CALIBRATION_FACTOR * hdfs_chunk_size * flops_per_mb * MSG_host_get_speed(h);
}


//TODO:  calibrate move tasks cost!

double get_bytes_to_move()       // get data from the input file for the shuffling phase
{
	double INIT_CALIBRATION_FACTOR =1600000.0007100;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / mappers);
}

double get_bytes_to_reduce_move()
{
	double INIT_CALIBRATION_FACTOR = 6000.0077100;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers_2);//0.0077100
}


//TODO:  set shuffle tasks cost!

double get_bytes_to_shuffle()
{
	double INIT_CALIBRATION_FACTOR = 0.094;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_2()
{
	double INIT_CALIBRATION_FACTOR = 0.051;//0.51;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_3()
{
	double INIT_CALIBRATION_FACTOR = 0.050;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_4()
{
	double INIT_CALIBRATION_FACTOR = 0.044;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_5()
{
	double INIT_CALIBRATION_FACTOR = 0.054;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_6()
{
	double INIT_CALIBRATION_FACTOR = 0.064;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_7()
{
	double INIT_CALIBRATION_FACTOR = 0.074;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_8()
{
	double INIT_CALIBRATION_FACTOR = 0.084;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_9()
{
	double INIT_CALIBRATION_FACTOR = 0.094;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

double get_bytes_to_shuffle_10()
{
	double INIT_CALIBRATION_FACTOR = 0.05;
	return INIT_CALIBRATION_FACTOR * (hdfs_chunk_size_bytes / reducers);
}

//TODO:  set reduce tasks cost!

double get_reduce_cost(msg_host_t h)
{
	double flops_per_mb =0.094164;
	double rand_num = random_int(20000,40000);
	 flops_per_mb *= rand_num/20000;
	return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

/* reduce cost for reducers2*/
double get_reduce_cost_2(msg_host_t h)
{

   double flops_per_mb =0.09512;
   double rand_num = random_int(20000,40000);
   flops_per_mb *= rand_num/20000;
   return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

/* reduce cost for reducers2*/
double get_reduce_cost_3(msg_host_t h)
{

	double flops_per_mb =0.094912;//0.0011
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
	return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_4(msg_host_t h)
{
	double flops_per_mb =0.08892;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
	return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_5(msg_host_t h)
{
	double flops_per_mb =0.090804;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_6(msg_host_t h)
{
	double flops_per_mb =0.09412;//0.00054;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_7(msg_host_t h)
{
	double flops_per_mb =0.093233;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}
double get_reduce_cost_8(msg_host_t h)
{
	double flops_per_mb =0.09364;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}


double get_reduce_cost_9(msg_host_t h)
{
	double flops_per_mb =0.08943;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}


double get_reduce_cost_10(msg_host_t h)
{
	double flops_per_mb = 0.084296;
	double rand_num = random_int(20000,40000);
	flops_per_mb *= rand_num/20000;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_11(msg_host_t h)
{
	double flops_per_mb = 0.00013600;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_12(msg_host_t h)
{
	double flops_per_mb =  0.00013230;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_13(msg_host_t h)
{
	double flops_per_mb = 0.0071;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_14(msg_host_t h)
{
	double flops_per_mb = 0.0011;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_15(msg_host_t h)
{
	double flops_per_mb = 0.0071;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

double get_reduce_cost_16(msg_host_t h)
{
	double flops_per_mb = 0.0081;
    return REDUCE_CALIBRATION_FACTOR * (input_size / reducers) * flops_per_mb * MSG_host_get_speed(h);
}

void call_add_map(struct HdmsgHost * hdmsg_host, int i)
{
	switch(i)
	{
		case 1:
			add_map_task(hdmsg_host, get_map_cost_1(hdmsg_host->host));
			break;
		case 2:
			add_map_task_2(hdmsg_host, get_map_cost_2(hdmsg_host->host));
			break;
		case 3:
			add_map_task_3(hdmsg_host, get_map_cost_3(hdmsg_host->host));
			break;
		case 4:
			add_map_task_4(hdmsg_host, get_map_cost_4(hdmsg_host->host));
			break;
		case 5:
			add_map_task_5(hdmsg_host, get_map_cost_5(hdmsg_host->host));
			break;
		case 6:
			add_map_task_6(hdmsg_host, get_map_cost_6(hdmsg_host->host));
			break;
		case 7:
			add_map_task_7(hdmsg_host, get_map_cost_7(hdmsg_host->host));
			break;
		case 8:
			add_map_task_8(hdmsg_host, get_map_cost_8(hdmsg_host->host));
			break;
		case 9:
			add_map_task_9(hdmsg_host, get_map_cost_9(hdmsg_host->host));
			break;
		case 0:
			add_map_task_0(hdmsg_host, get_map_cost_0(hdmsg_host->host));
			break;
		case 11:
			add_map_task_11(hdmsg_host, get_map_cost_11(hdmsg_host->host));
			break;
		case 12:
			add_map_task_12(hdmsg_host,  get_map_cost_12(hdmsg_host->host));
			break;
	}
}


void distribution(long number_of_input_chunks, int i)
{
	 char * key;
	 struct HdmsgHost * hdmsg_host;
	 xbt_dict_cursor_t cursor = NULL;

	 while (number_of_input_chunks > 0)
	 {
		 xbt_dict_foreach(hosts, cursor, key, hdmsg_host)
	     {
			 if (number_of_input_chunks > 0 && hdmsg_host->is_worker)
	            {
				 	call_add_map(hdmsg_host,i);
	            	number_of_input_chunks--;
	            }
	     }
	  }
}

void distributeHdfsChunks()
{
   long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 1);
}

void distributeHdfsChunks_2()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 2);
}

void distributeHdfsChunks_3()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 3);
}

void distributeHdfsChunks_4()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 4);
}

void distributeHdfsChunks_5()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 5);
}

void distributeHdfsChunks_6()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 6);
}

void distributeHdfsChunks_7()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 7);
}

void distributeHdfsChunks_8()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 8);
}

void distributeHdfsChunks_9()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 9);
}

void distributeHdfsChunks_0()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 0);
}

void distributeHdfsChunks_11()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 11);
}

void distributeHdfsChunks_12()
{
	long number_of_input_chunks = input_size_bytes / hdfs_chunk_size_bytes;
	distribution(number_of_input_chunks, 12);
}


static int Complement_Task()
 {
	  msg_task_t newtask;
	  	  double load = 1E10;
	  newtask = MSG_task_create("job", load,0, NULL);
	  MSG_task_execute(newtask);
	  MSG_task_destroy(newtask);
		return 0;
 }

static int Complement_Task_1()
 {
	  msg_task_t newtask;
	 double load = 10E9;
	  newtask = MSG_task_create("job", load,0, NULL);
	  MSG_task_execute(newtask);
	  MSG_task_destroy(newtask);
		return 0;
 }

static int Complement_Task_2()
  {
	  msg_task_t newtask_2;
	  double start_time =  MSG_get_clock();
	  newtask_2 = MSG_task_create("job", 100E5, 0, NULL);
	  MSG_task_execute(newtask_2);
	  double finish_time = MSG_get_clock() - start_time;
	  MSG_task_destroy(newtask_2);
	  return 0;
  }

static int Complement_Task_9()
  {
	  msg_task_t newtask_2;
	  double start_time =  MSG_get_clock();
	  newtask_2 = MSG_task_create("job", 1E10, 0, NULL);
	  MSG_task_execute(newtask_2);
	  double finish_time = MSG_get_clock() - start_time;
	  MSG_task_destroy(newtask_2);
	  return 0;
  }

static int Dummy_Task_6()
  {
	  msg_task_t newtask_2;
	  double start_time =  MSG_get_clock();
	  newtask_2 = MSG_task_create("job", 1E6, 0, NULL);
	  MSG_task_execute(newtask_2);
	  double finish_time = MSG_get_clock() - start_time;
	  MSG_task_destroy(newtask_2);
	  return 0;
  }

static int Complement_Task_10()
  {
	  msg_task_t newtask_2;
	  double start_time =  MSG_get_clock();
	  newtask_2 = MSG_task_create("job", 1E10, 0, NULL);
	  MSG_task_execute(newtask_2);
	  double finish_time = MSG_get_clock() - start_time;
	  MSG_task_destroy(newtask_2);
	  return 0;
  }

static int Complement_Task_7()
  {
	  msg_task_t newtask_2;
	  double start_time =  MSG_get_clock();
	  newtask_2 = MSG_task_create("job", 100E8, 0, NULL);
	  MSG_task_execute(newtask_2);
	  double finish_time = MSG_get_clock() - start_time;
	  MSG_task_destroy(newtask_2);
	  return 0;
  }

static int Complement_Task_3()
  {
	  msg_task_t newtask_2;
	 // double rand_num = random_num(20000,40000);
	  double load = 10E8;
	 // load *= (rand_num/20000);
	  newtask_2 = MSG_task_create("job", load,0, NULL);
	  MSG_task_execute(newtask_2);
	  MSG_task_destroy(newtask_2);
	  return 0;
  }


static int Complement_Task_4()
   {

	msg_task_t newtask;
	double load = 98095000;
	 	 newtask = MSG_task_create("job", load, 0, NULL);
 	  MSG_task_execute(newtask);
 	  MSG_task_destroy(newtask);
  	  return 0;
   }

static int Complement_Task_8()
   {
	msg_task_t newtask;
	double load = 98090;
 	 newtask = MSG_task_create("job", load, 0, NULL);
 	  MSG_task_execute(newtask);
 	  MSG_task_destroy(newtask);

 	  return 0;
   }


static int Complement_Task_5()
   {
	 msg_task_t newtask;
	 double load = 980950000;
 	 newtask = MSG_task_create("job", load, 0, NULL);
 	  MSG_task_execute(newtask);
 	  MSG_task_destroy(newtask);
 	  return 0;
   }


int TaskReceive(int argc, char * argv[])
{
    int res;
    msg_task_t task = NULL;
    res = MSG_task_receive(&(task), MSG_process_get_name(MSG_process_self()));
    xbt_assert(res == MSG_OK, "MSG_task_get failed: Task Receive");
    MSG_task_destroy(task);
    return 0;
}
